### ISSUE TITLE
Invalid header

### ISSUE THREAD

**Issue by kaninaba94** [fundakol/pytest-jira-xray#84]
Uploading my test results with `pytest --jira-xray --client-secret-auth` (as per [instructions](https://pypi.org/project/pytest-jira-xray/#description)), I get 

```
test_example.py ..                                                                                                                                                                                                      [100%]Traceback (most recent call last):
  File "/home/user/.pyenv/versions/learn/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/_pytest/config/__init__.py", line 166, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pluggy/_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/_pytest/main.py", line 305, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pluggy/_callers.py", line 133, in _multicall
    teardown[0].send(outcome)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/_pytest/terminal.py", line 857, in pytest_sessionfinish
    outcome.get_result()
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pytest_xray/xray_plugin.py", line 180, in pytest_sessionfinish
    self.issue_id = self.publisher.publish(results)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pytest_xray/xray_publisher.py", line 129, in publish
    response_data = self._send_data(self.endpoint_url, self.auth, data)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/pytest_xray/xray_publisher.py", line 100, in _send_data
    response = requests.request(
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/user/.pyenv/versions/3.8.10/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/user/.pyenv/versions/3.8.10/lib/python3.8/http/client.py", line 1293, in _send_request
    self.putheader(hdr, value)
  File "/home/user/.pyenv/versions/learn/lib/python3.8/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/home/user/.pyenv/versions/3.8.10/lib/python3.8/http/client.py", line 1230, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b"Bearer <!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content=IE=edge><title>Oops, you&#39;ve found a dead link. - JIRA</title><link type='text/css' rel='stylesheet' href='/static-assets/metal-all.css' media='all'><script src='/static-assets/metal-all.js'></script><meta name=decorator content=none /></head><body class= error-page error404><script type=text/javascript>document.body.className +=  js-enabled;</script><div id=page><header id=header role=banner></header><!-- #header --><section id=content role=main><div class=aui-page-panel><div class=aui-page-panel-inner><section class=aui-page-panel-content lowerContent><div id=error-state><span class=error-type></span><h1>Oops, you&#39;ve found a dead link.</h1><ul><li>Go back to the <a href=javascript:window.history.back()>previous page</a></li><li>Go to the <a href=/secure/MyJiraHome.jspa>Home Page</a></li></ul></div></section><!-- .aui-page-panel-content --></div><!-- .aui-page-panel-inner --></div><!-- .aui-page-panel --></section><!-- #content --><footer id=footer role=contentinfo><section class=footer-body>\n\n\n<ul class=atlassian-footer>\n    <li>\n        Atlassian JIRA <a class=seo-link href=https://www.atlassian.com/software/jira>Project Management Software</a>\n\n                                    \n                        \n        <span id=footer-build-information>(v1001.0.0-SNAPSHOT#100233-<span title='b4f309b7403c6ec1360911f686faf41e7d904ce2' data-commit-id='b4f309b7403c6ec1360911f686faf41e7d904ce2}'>sha1:b4f309b</span>)</span>\n    </li>\n    <li>\n        <a id=about-link href=/secure/AboutPage.jspa>About JIRA</a>\n    </li>\n    <li>\n                        <a id=footer-report-problem-link href=/secure/ContactAdministrators!default.jspa>Report a problem</a>\n    </li>\n</ul>\n<div id=footer-logo><a href=http://www.atlassian.com/ rel=nofollow>Atlassian</a></div></section></footer><!-- #footer --></div><!-- #page --></body></html>"
```

**Comment by fundakol** [comment]
Check your JIRA API Url in the `XRAY_API_BASE_URL` variable because you got in response:
```
Oops, you've found a dead link.
```

**Comment by kaninaba94** [comment]
Wait, what base URL should I use? Something like `https://<company>.atlassian.net`, right?

**Comment by kaninaba94** [comment]
This link holds the answer: https://community.atlassian.com/t5/Jira-questions/How-to-define-Xray-s-endpoint-base-URL/qaq-p/1940320
