### ISSUE TITLE
ExitCode cannot be imported

### ISSUE THREAD

**Issue by kaninaba94** [fundakol/pytest-jira-xray#85]
When trying to run `pytest --jira-xray --client-secret-auth` after having set all the env vars, I get:

```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/repo/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/_pytest/config/__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/_pytest/config/__init__.py", line 194, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/pluggy/_callers.py", line 133, in _multicall
    teardown[0].send(outcome)
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/_pytest/config/__init__.py", line 654, in pytest_cmdline_parse
    self.parse(args)
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/_pytest/config/__init__.py", line 871, in parse
    self._preparse(args, addopts=addopts)
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/_pytest/config/__init__.py", line 816, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/pluggy/_manager.py", line 364, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/user/.pyenv/versions/3.8.10/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/user/.pyenv/versions/3.8.10/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 296, in load_module
    six.exec_(co, mod.__dict__)
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/pytest_xray/plugin.py", line 24, in <module>
    from pytest_xray.xray_plugin import XrayPlugin
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 296, in load_module
    six.exec_(co, mod.__dict__)
  File "/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/pytest_xray/xray_plugin.py", line 8, in <module>
    from _pytest.config import Config, ExitCode
ImportError: cannot import name 'ExitCode' from '_pytest.config' (/home/user/.pyenv/versions/repo/lib/python3.8/site-packages/_pytest/config/__init__.py)

```

**Comment by fundakol** [comment]
Which version of pytest are you using?

**Comment by fundakol** [comment]
Closed due to no feedback from reporter
